import { c as create_ssr_component, v as validate_component } from "../../chunks/ssr.js";
const Header = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  return `<nav class="navbar navbar-expand-lg bg-body-tertiary border-bottom border-body"><div class="container-fluid"><a class="navbar-brand" href="/" data-svelte-h="svelte-yrktzc">Titan</a> <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation" data-svelte-h="svelte-1wyjgjz"><span class="navbar-toggler-icon"></span></button> <div class="collapse navbar-collapse" id="navbarSupportedContent"><ul class="navbar-nav me-auto mb-2 mb-lg-0"><li class="position-absolute top-0 end-0 py-2 px-3">${`<div class="btn-group" data-svelte-h="svelte-jezbuw"><a class="btn btn-primary dropdown-toggle" data-bs-toggle="dropdown" data-bs-display="static" aria-expanded="false" aria-current="page" href="/signin">Autenticação</a> <ul class="dropdown-menu dropdown-menu-end dropdown-menu-start"><li><a class="dropdown-item" href="/signin">Entrar na conta</a></li> <li><a class="dropdown-item" href="/signup">Criar conta</a></li></ul></div>`}</li></ul> <form class="position-absolute top-0 start-50 translate-middle-x py-2 px-4" role="search" data-svelte-h="svelte-wfenwi"><div class="input-group mb-3"><input class="form-control" type="search" name="q" placeholder="Faça uma pesquisa" aria-label="Search"> <button class="input-group-text" id="basic-addon1" type="submit"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16"><path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001q.044.06.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1 1 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0"></path></svg></button></div></form></div></div></nav>`;
});
const Layout = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  return `<div class="app">${validate_component(Header, "Header").$$render($$result, {}, {}, {})} ${slots.default ? slots.default({}) : ``}</div>`;
});
export {
  Layout as default
};
